### ISSUE TITLE
Feature suggestion: Add park position functionality for linear actuators

### ISSUE THREAD

**Issue by Dirt-e** [motion4sim/AASD15A-Servo-Controller-for-Motion-Simrigs#3]
Hey @motion4sim,

Super high-quality real-time motion controller you made there! Lovin' it!

I've got a feature suggestion:
Whenever I flip the switch to "Online" my linear actators smoothly run up to the park position (50% position) and then my software takes over from there. Thing is, I would like this takeover to take place in the 0% position already.

Would it be possible to allow a "Park Position" parameter to be set in the controller for linear actuators as well? Analogous to how it's  handled on rotary actuators?

Cheerst,... Dirty :-)

**Comment by motion4sim** [comment]
function included now
